instaProj/Models/Follow.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;

namespace instaProj.Models
{
    public class Follow
    {
        public int Id { get; set; }
        public int User_Id_Followed { get; set; } //Seguidor
        public int User_Id_Following {  get; set; } //Seguindo
        [NotMapped]
        [JsonIgnore]
        public User? User_Followed { get; set; }
        [NotMapped]
        [JsonIgnore]
        public User? User_Following { get; set; }

        // select cont(*) from Follow where User_Id_Followed = 1 - User 1 tem x seguidores
    }
}

instaProj/Controllers/AplicationController.cs
using instaProj.Models;
using Microsoft.AspNetCore.Mvc;
using SixLabors.ImageSharp.Formats.Jpeg;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SixLabors.ImageSharp;
using SixLabors.ImageSharp.Processing;
using System.Net;
using System.ComponentModel.DataAnnotations;

namespace instaProj.Controllers
{
    public class AplicationController : Controller
    {
        private readonly Contexto _context;

        public AplicationController(Contexto context)
        {
            _context = context;
        }
        public IActionResult Main(string page)
        {
            if (HttpContext.Session.GetString("USERLOGADO") != null && int.TryParse(HttpContext.Session.GetString("USERLOGADO"), out int id))
            {
                User? pessoaLogada = _context.Users.FirstOrDefault(m => m.Id == id);

                if (pessoaLogada != null)
                {
                    ViewBag.User = pessoaLogada;
                    ViewBag.Following = _context.Follows.Where(m => m.User_Id_Followed == id).Include(m => m.User_Following).ToList() ?? new List<Follow>();
                    ViewBag.Followed = _context.Follows.Where(m => m.User_Id_Following == id).Include(m => m.User_Followed).ToList() ?? new List<Follow>();
                    ViewBag.MainPage = page ?? "ForYou";
                    List<Post> post = _context.Posts.Where(m => m.User_Id == id && m.Private != true).Include(m => m.User).OrderBy(m => m.DatePub).Reverse().ToList() ?? new List<Post>();
                    foreach (Post p in post) 
                    {
                        p.Archives = _context.Archives.Where(m => m.Post_Id == p.Id).ToList();

                        // Verifica se há uma avaliação (favorito) do usuário para o post
                        var ratingPostExists = _context.Ratings.Any(m => m.Post_Id == p.Id && m.User_Id == id);

                        // Atribui o valor de 'Rating' com base na existência da avaliação
                        p.Rating = ratingPostExists;

                        p.Comment = _context.Comments.Where(m => m.Post_Id == p.Id).Include(m => m.User).ToList() ?? new List<Comment>();

                        foreach(Comment c in p.Comment)
                        {
                            var ratingCommentExists = _context.Ratings.Any(m => m.Comment_Id == c.Id && m.User_Id == id);

                            c.Rating = ratingCommentExists;
                        }
                    }
                    ViewBag.MyPosts = post;
                    if (page == "UpdateUser")
                    {
                        ViewBag.Model = ViewBag.User;
                    }
                    else
                    {
                        ViewBag.Model = null;
                    }
                    post = _context.Posts.Where(m => m.User_Id != id && m.Private != true).Include(m => m.User).ToList() ?? new List<Post>();
                    foreach (Post p in post)
                    {
                        p.Archives = _context.Archives.Where(m => m.Post_Id == p.Id).ToList();

                        var ratingPostExists = _context.Ratings.Any(m => m.Post_Id == p.Id && m.User_Id == id);

                        p.Rating = ratingPostExists;

                        p.Comment = _context.Comments.Where(m => m.Post_Id == p.Id).Include(m => m.User).ToList() ?? new List<Comment>();

                        foreach (Comment c in p.Comment)
                        {
                            var ratingCommentExists = _context.Ratings.Any(m => m.Comment_Id == c.Id && m.User_Id == id);

                            c.Rating = ratingCommentExists;
                        }
                    }
                    ViewBag.OtherPosts = post;
                }
                return View();
            }
            return View();
        }

        public IActionResult MyPage()
        {
            if (HttpContext.Session.GetString("USERLOGADO") != null && int.TryParse(HttpContext.Session.GetString("USERLOGADO"), out int id))
            {
                User? pessoaLogada = _context.Users.FirstOrDefault(m => m.Id == id);

                if (pessoaLogada != null)
                {
                    ViewBag.User = pessoaLogada;
                }
                return View();
            }
            return View();
        }
        public IActionResult ForYou()
        {
            return View();
        }

        public IActionResult UpdateUser()
        {
            return View();
        }

        public IActionResult Menu()
        {
            return View();
        }
        public IActionResult Follows()
        {
            return View();
        }
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Favorite(int post)
        {
            if (post != 0 && HttpContext.Session.GetString("USERLOGADO") != null && int.TryParse(HttpContext.Session.GetString("USERLOGADO"), out int userId))
            {
                // Verifica se já existe uma entrada de Rating para o usuário atual e o post específico
                Rating? rating = await _context.Ratings.FirstOrDefaultAsync(r => r.User_Id == userId && r.Post_Id == post);

                if (rating == null)
                {
                    // Se não existe, cria uma nova entrada de Rating
                    Rating r = new Rating
                    {
                        User_Id = userId,
                        Post_Id = post,
                        Comment_Id = 0,
                        SubComment_Id = 0
                    };
                    _context.Ratings.Add(r);
                }
                else
                {
                    // Se já existe uma entrada de Rating, remove-a
                    _context.Ratings.Remove(rating);
                }

                // Salva as mudanças no banco de dados apenas uma vez
                await _context.SaveChangesAsync();

                // Retorna o status da operação como JSON
                return Json(new { success = true });
            }

            // Retorna um erro caso não seja possível processar a requisição
            return BadRequest("Erro ao favoritar o post.");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> FavoriteComment(int post)
        {
            if (post != 0 && HttpContext.Session.GetString("USERLOGADO") != null && int.TryParse(HttpContext.Session.GetString("USERLOGADO"), out int userId))
            {
                // Verifica se já existe uma entrada de Rating para o usuário atual e o post específico
                Rating? rating = await _context.Ratings.FirstOrDefaultAsync(r => r.User_Id == userId && r.Comment_Id == post);

                if (rating == null)
                {
                    // Se não existe, cria uma nova entrada de Rating
                    Rating? r = new Rating
                    {
                        User_Id = userId,
                        Post_Id = 0,
                        Comment_Id = post,
                        SubComment_Id = 0
                    };
                    _context.Ratings.Add(r);
                }
                else
                {
                    // Se já existe uma entrada de Rating, remove-a
                    _context.Ratings.Remove(rating);
                }

                // Salva as mudanças no banco de dados apenas uma vez
                await _context.SaveChangesAsync();

                // Retorna o status da operação como JSON
                return Json(new { success = true });
            }

            // Retorna um erro caso não seja possível processar a requisição
            return BadRequest("Erro ao favoritar o post.");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Follow(int followedId, int followingId)
        {
                var follow = new Follow
                {
                    User_Id_Following = followingId,
                    User_Id_Followed = followedId
                };
                if (!_context.Follows.Contains(follow))
                {
                    _context.Follows.Add(follow);
                    await _context.SaveChangesAsync();
                }
            return RedirectToAction("Main");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Unfollow(int followedId, int followingId)
        {
                var follow = await _context.Follows.FirstOrDefaultAsync(f => f.User_Id_Following == followingId && f.User_Id_Followed == followedId);
                if (follow != null)
                {
                    _context.Follows.Remove(follow);
                    await _context.SaveChangesAsync();
            }
            return RedirectToAction("Main");
        }

        [HttpPost]
        public async Task<IActionResult> CreatePostComment(int postId, string description)
        {
            if (HttpContext.Session.GetString("USERLOGADO") != null && int.TryParse(HttpContext.Session.GetString("USERLOGADO"), out int userId))
            {
                var comment = new Comment
                {
                    Description = description,
                    Ocult = false,
                    User_Id = userId,
                    Post_Id = postId
                };

                _context.Comments.Add(comment);
                await _context.SaveChangesAsync();

                var newComment = await _context.Comments
                    .Include(c => c.User)
                    .Where(c => c.Id == comment.Id)
                    .Select(c => new
                    {
                        c.Id,

instaProj/Views/Aplication/CommentShow.cshtml
@model instaProj.Models.Comment


<div class="col-1 d-flex justify-content-center align-items-center mt-3">
    <img src="@(Model.User.PictureLocal ?? "/images/ppic.png")" alt="" class="user">
</div>
<div class="d-flex flex-column gap-1 col-10 mt-3">
    <h5 class="no-config">@Model.User.Name</h5>
    <p class="no-config" style="text-align: left; word-wrap: break-word">@Model.Description</p>
</div>

<div class="col-1 d-flex justify-content-center align-items-center">
    @{
        bool isFavorited = Model.Rating; //p.Rating indica se o post foi favoritado pelo usuário
    }

    <label class="fav" style="width: 50px; background-color:rebeccapurple" onclick="toggleFavorite(@Model.Id)">
        <input type="checkbox" @if (isFavorited)
        {
            <text>checked</text>
        }>
        <svg class="star-regular" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 576 512">
            <!-- Ícone de estrela Vazia -->
            <path d="M287.9 0c9.2 0 17.6 5.2 21.6 13.5l68.6 141.3 153.2 22.6c9 1.3 16.5 7.6 19.3 16.3s.5 18.1-5.9 24.5L433.6 328.4l26.2 155.6c1.5 9-2.2 18.1-9.6 23.5s-17.3 6-25.3 1.7l-137-73.2L151 509.1c-8.1 4.3-17.9 3.7-25.3-1.7s-11.2-14.5-9.7-23.5l26.2-155.6L31.1 218.2c-6.5-6.4-8.7-15.9-5.9-24.5s10.3-14.9 19.3-16.3l153.2-22.6L266.3 13.5C270.4 5.2 278.7 0 287.9 0zm0 79L235.4 187.2c-3.5 7.1-10.2 12.1-18.1 13.3L99 217.9 184.9 303c5.5 5.5 8.1 13.3 6.8 21L171.4 443.7l105.2-56.2c7.1-3.8 15.6-3.8 22.6 0l105.2 56.2L384.2 324.1c-1.3-7.7 1.2-15.5 6.8-21l85.9-85.1L358.6 200.5c-7.8-1.2-14.6-6.1-18.1-13.3L287.9 79z"></path>
        </svg>
        <svg class="star-solid" xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 576 512">
            <!-- Ícone de estrela preenchida -->
            <path d="M316.9 18C311.6 7 300.4 0 288.1 0s-23.4 7-28.8 18L195 150.3 51.4 171.5c-12 1.8-22 10.2-25.7 21.7s-.7 24.2 7.9 32.7L137.8 329 113.2 474.7c-2 12 3 24.2 12.9 31.3s23 8 33.8 2.3l128.3-68.5 128.3 68.5c10.8 5.7 23.9 4.9 33.8-2.3s14.9-19.3 12.9-31.3L438.5 329 542.7 225.9c8.6-8.5 11.7-21.2 7.9-32.7s-13.7-19.9-25.7-21.7L381.2 150.3 316.9 18z"></path>
        </svg>
    </label>
</div>

<script>
    let isFavoriteRequestInProgress = false;

    function toggleFavorite(postId) {
        if (isFavoriteRequestInProgress) return;

        isFavoriteRequestInProgress = true;

        $.ajax({
            type: "POST",
            url: '@Url.Action("FavoriteComment", "Aplication")',
            data: {
                post: postId,
                __RequestVerificationToken: $('input[name="__RequestVerificationToken"]').val()
            },
            success: function (response) {
                if (!response.success) {
                    alert('Erro ao realizar a operação.');
                }
            },
            error: function (error) {
                console.error('Erro:', error);
            },
            complete: function () {
                isFavoriteRequestInProgress = false;
            }
        });
    }
</script>

instaProj/Views/Aplication/Configuration.cshtml
@{
    ViewBag.MainPage = "Configuration";
}

@* BOTOES DE CONFIG *@
<div class="maxW d-flex gap-3 flex-column">
    <div>
        <button class="maxW btn btnConfig d-flex justify-content-between">
            Posts arquivados
            <svg width="64px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#292929"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="2.352"></g><g id="SVGRepo_iconCarrier"> <path d="M5 12H19M19 12L13 6M19 12L13 18" stroke="#292929" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
        </button>
    </div>
    <div>
        <button class="maxW btn btnConfig d-flex justify-content-between">
            Mudar senha
            <svg width="64px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#292929"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="2.352"></g><g id="SVGRepo_iconCarrier"> <path d="M5 12H19M19 12L13 6M19 12L13 18" stroke="#292929" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
        </button>
    </div>
    <div>
        <button class="maxW btn btnConfig d-flex justify-content-between" data-bs-toggle="modal" data-bs-target="#emailModal">
            Mudar e-mail
            <svg width="64px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#292929"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round" stroke="#CCCCCC" stroke-width="2.352"></g><g id="SVGRepo_iconCarrier"> <path d="M5 12H19M19 12L13 6M19 12L13 18" stroke="#292929" stroke-width="1.2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
        </button>
    </div>
</div>

@* POP-UP POSTS *@

@* POP-UP SENHA *@

@* POP-UP EMAIL *@

instaProj/Views/Aplication/Follows.cshtml
@{
    ViewData["Title"] = "Página de Seguidores";
    int contar = ((IEnumerable<object>)ViewBag.Following).Count();
    int contar2 = ((IEnumerable<object>)ViewBag.Followed).Count();
}

<div class="col">
    <div class="no-config p-3">
        <div class="row">
            <div class="col box-follow-select" id="following" onclick="changeList(1)">
                <h6 class="no-config text-select">SEGUINDO (@contar)</h6>
            </div>
            <div class="col box-follow-select" id="followed" onclick="changeList(2)">
                <h6 class="no-config text-select">SEGUIDORES (@contar2)</h6>
            </div>
        </div>
        <div class="w-100 col d-flex flex-column justify-content-center align-items-center" style="padding-top: 15px;">
            <div id="seguindo-lista" class="w-100">
                @if (ViewBag.Following != new List<Follow>())
                {
                    @foreach (var following in ViewBag.Following)
                    {
                        <div class="card w-100 mt-3">
                            <div class="card-body p-4 text-black">
                                <div class="d-flex align-items-center">
                                    <div class="flex-shrink-0">
                                        @if (following.User_Following?.PictureLocal != null)
                                        {
                                            <img src="@following.User_Following?.PictureLocal"
                                                 alt="Imagem genérica" class="img-fluid rounded-circle"
                                                 style="width: 70px; height: 70px;">
                                        }
                                        else
                                        {
                                            <img src="https://p2.trrsf.com/image/fget/cf/1200/900/middle/images.terra.com/2024/03/26/kaiju-no-8-to1unk3bslyo.jpg"
                                                 alt="Imagem genérica" class="img-fluid rounded-circle"
                                                 style="width: 70px; height: 70px;">
                                        }
                                    </div>
                                    <div class="flex-grow-1 ms-3 h-100 d-flex align-content-center">
                                        <h6 style="font-size: 1.5rem; color: #e8e8e8; overflow: hidden; text-overflow:ellipsis; height:30px">@following.User_Following?.Name</h6>
                                    </div>
                                    <form asp-action="Unfollow" asp-controller="Aplication" method="post">
                                        @Html.AntiForgeryToken()
                                        <input type="hidden" name="followedId" value="@following.User_Followed.Id" />
                                        <input type="hidden" name="followingId" value="@following.User_Following.Id" />
                                        <button type="submit" class="btn btn-outline-light btn-rounded btn-sm d-flex justify-content-center">Unfollow</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <h5>Você não está seguindo ninguém ainda.</h5>
                }
            </div>

            <div id="seguidores-lista" style="display: none;" class="w-100">
                @if (ViewBag.Followed != new List<Follow>())
                {
                    @foreach (var follower in ViewBag.Followed)
                    {
                        <div class="card w-100 mt-3">
                            <div class="card-body p-4 text-black">
                                <div class="d-flex align-items-center">
                                    <div class="flex-shrink-0">
                                        @if (follower.User_Following?.PictureLocal != null)
                                        {
                                            <img src="@follower.User_Followed?.PictureLocal"
                                                 alt="Imagem genérica" class="img-fluid rounded-circle"
                                                 style="width: 70px; height: 70px;">
                                        }
                                        else
                                        {
                                            <img src="https://www.otempo.com.br/content/dam/otempo/editorias/entretenimento/filmes-e-series/2023/10/entretenimento-pluto-como-o-anime-da-netflix-se-conecta-a-astro-boy-1708750812.jpeg"
                                                 alt="Imagem genérica" class="img-fluid rounded-circle"
                                                 style="width: 70px; height: 70px;">
                                        }
                                    </div>
                                    <div class="flex-grow-1 ms-3 h-100 d-flex align-content-center">
                                        <h6 style="font-size: 1.5rem; color: #e8e8e8; overflow: hidden; text-overflow:ellipsis;">@follower.User_Followed?.Name</h6>
                                    </div>
                                    @if (!((List<Follow>)ViewBag.Following).Exists(x => x.User_Id_Following == follower.User_Id_Followed && x.User_Id_Followed == follower.User_Id_Following))
                                    {
                                        Console.WriteLine("Opaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa");
                                        <form asp-action="Follow" asp-controller="Aplication" method="post">
                                            @Html.AntiForgeryToken()
                                            <input type="hidden" name="followedId" value="@follower.User_Following.Id" />
                                            <input type="hidden" name="followingId" value="@follower.User_Followed.Id" />
                                            <button type="submit" class="btn btn-outline-light btn-rounded btn-sm d-flex justify-content-center"> Follow </button>
                                        </form>
                                    }
                                    else
                                    {
                                        <form asp-action="Unfollow" asp-controller="Aplication" method="post">
                                            @Html.AntiForgeryToken()
                                            <input type="hidden" name="followedId" value="@ViewBag.User.Id" />
                                            <input type="hidden" name="followingId" value="@follower.User_Followed.Id" />
                                            <button type="submit" class="btn btn-outline-light btn-rounded btn-sm d-flex justify-content-center"> Unfollow </button>
                                        </form>
                                    }

                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <h5>Você não tem seguidores ainda.</h5>
                }
            </div>
        </div>
    </div>
</div>

<style>
    .box-follow {
        background-color: gray;
        height: 45%;
        margin: 1rem;
        border-radius: 15px;
        overflow: hidden;
    }

    .box-follow-select {
        text-align: center;
        height: 30px !important;
        display: flex;
        align-items: center;
        justify-content: center;
        color: #292929;
        border-radius: 50px;
        cursor: pointer;
    }

        .box-follow-select:hover {
            background-color: #f5f898;
            border-radius: 50px;
        }

    .select-follow {
        border-radius: 50px;
        display: inline-block;
        text-decoration: underline 3px;
        text-decoration-color: #f4f440;
    }

    .card {
        background-color: #292929;
        border-radius: 15px;
    }
</style>

<script>
    var followingTab = document.getElementById('following');
    var followersTab = document.getElementById('followed');
    var followingList = document.getElementById('seguindo-lista');
    var followersList = document.getElementById('seguidores-lista');

    followingTab.classList.add('select-follow');
    followingList.style.display = 'block';
    followersList.style.display = 'none';

    function changeList(index) {
        if (index === 1) {
            followingTab.classList.add('select-follow');
            followersTab.classList.remove('select-follow');
            followingList.style.display = 'block';
            followersList.style.display = 'none';
        } else {
            followingTab.classList.remove('select-follow');
            followersTab.classList.add('select-follow');
            followingList.style.display = 'none';
            followersList.style.display = 'block';
        }
    }
</script>

instaProj/Views/Aplication/Main.cshtml
@{
    ViewData["Title"] = "Bem-Te-Vi";
    string view = ViewBag.MainPage;
}



<div class="row" style="width: 100%; height: 100%">
    <div class="col vll no-config" style="height: 100%">
        <partial name="Menu" />
    </div>
    <div class="col-6 no-config" style="height: 100%" id="mainContainer">
        @if (ViewBag.Model != null)
        {
            <partial name="@view" model="@ViewBag.User" />
            /* - Partial Indexar uma página na outra - */
        }
        else
        {
            <partial name="@view" />
        }

    </div>
    <div class="col vlr no-config" style="height: 100%">
        <partial name="Follows" />
    </div>
</div>


<style>
    .select:hover {
        background-color: lightgray;
    }

    .no-config {
        padding: 0px;
        margin: 0px;
    }

    .row {
        margin: 0px;
        flex-wrap: nowrap;
    }

    .col {
        height: 100%;
    }
</style>

instaProj/Views/Aplication/Menu.cshtml
<div class="d-flex flex-column align-items-center maxW justify-content-between" style="height:100%; padding-top: 5rem;">
    <div class="d-flex flex-column maxW">
        <div class="d-flex gap-3 align-items-center justify-content-start ps-4">
            <div class="logo">
                <img src="@(ViewBag.User.PictureLocal ?? "/images/ppic.png")" alt="" class="user">
            </div>
            <h2 class="no-config">@ViewBag.User.Name</h2>
        </div>
        <br />
        <div class="col">
            <a asp-action="Main" asp-controller="Aplication" asp-route-page="ForYou" class="maxW d-flex gap-2 align-items-center p-4 ps-5 select btn">
                <span class="material-symbols-outlined">
                    home
                </span>
                <h4 class="no-config">Home</h4>
            </a>
            <a asp-action="Main" asp-controller="Aplication" asp-route-page="MyPage" class="maxW d-flex gap-2 align-items-center p-4 ps-5 btn select">
                <span class="material-symbols-outlined">
                    person
                </span>
                <h4 class="no-config">Perfil</h4>
            </a>
            @* <a asp-action="Main" asp-controller="Aplication" asp-route-page="Configuration" class="maxW d-flex gap-2 align-items-center p-4 ps-5 btn select">
                <span class="material-symbols-outlined">
                    settings
                </span>
                <h4 class="no-config">Configurações</h4>
            </a> *@
            <div class="d-flex align-items-center gap-2 p-4 ps-5 select" data-bs-toggle="modal" data-bs-target="#npm-modal">
                <span class="material-symbols-outlined">
                    add
                </span>
                <h4 class="no-config">
                    Novo Post
                </h4>
            </div>
        </div>
        <hr class="maxW" />
    </div>

    <a asp-action="Logout" asp-controller="Users" class="maxW d-flex gap-2 align-items-center p-4 ps-5 btn select">
        <span class="material-symbols-outlined">
            logout
        </span>
        <h4 class="no-config">Logout</h4>
    </a>
</div>

<div class="modal" tabindex="-1" id="npm-modal">
    <div class="modal-dialog modal-dialog-centered d-flex justify-content-center align-items-center" style="max-width: none">
        <div class="modal-content" style="width: 50vw">
            <div class="modal-header">
                <h5 class="modal-title" id="npm-title">Novo post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="npm-body">
                <partial name="NewPost" />
            </div>
        </div>
    </div>
</div>

<style>
    .modal-content {
        background-color: #292929;
    }

    .modal-title {
        color: #e8e8e8;
    }

    .btn-close {
        background-color: white;
        color: white;
    }

</style>

<script>
    function Redirect(id) {
        var a = document.getElementById(id);
        console.log(a);
        a.click;
    }
</script>

instaProj/Views/Aplication/UpdateUser.cshtml
@model instaProj.Models.User

@{
    ViewData["Title"] = "UpdateUser";
}

<form asp-action="UpdateUser" asp-controller="Users" enctype="multipart/form-data" class="w-100 d-flex justify-content-center">
    <div class="maxW pe-5 ps-5 d-flex gap-3 flex-column mt-4">
        <div class="d-flex justify-content-center">
            <label for="profilePicture" style="cursor: pointer;">
                <img id="AttImage" src="@(Model.PictureLocal ?? "/images/ppic.png")" alt="Foto de perfil do usuário" style="border-radius: 50%; width: 150px; height: 150px;" />
            </label>
            <input asp-for="PictureLocal" type="file" id="profilePicture" class="form-control-file d-none" aria-label="Foto de Perfil do Usuário" />
            <span asp-validation-for="PictureLocal" class="text-danger"></span>
        </div>

        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

        <div class="form-floating mb-3">
            <input asp-for="Name" class="form-control" id="floatingInputName" placeholder="User123" aria-label="Nome do Usuário">
            <label asp-for="Name" for="floatingInputName">Usuário</label>
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Bio" class="control-label">Bio</label>
            <textarea asp-for="Bio" class="form-control" aria-label="Biografia do Usuário" maxlength="150"></textarea>
            <span asp-validation-for="Bio" class="text-danger"></span>
        </div>

        <div class="maxW d-flex justify-content-end">
            <div>
                <button class="btn btnPd2" asp-action="Main" asp-route-page="MyPage">Voltar</button>
            </div>
            <div class="p-1"></div>
            <div>
                <button type="submit" class="btn btnPd">Salvar</button>
            </div>
        </div>
        <input type="hidden" asp-for="Id" />
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

<style>
    body {
        display: flex;
        flex-direction: column;
        justify-content: center;
        overflow: hidden;
    }

    #AttImage {
        width: 150px;
        height: auto;
    }

    form {
        height: 90%;
    }

    .d-none {
        display: none;
    }
</style>

<script>
    $(document).ready(function () {
        $('#floatingInputPhone').mask('(00) 00000-0000');

        $('#profilePicture').change(function (e) {
            const file = e.target.files[0];
            if (file) {
                const reader = new FileReader();
                reader.onload = function (e) {
                    $('#AttImage').attr('src', e.target.result);
                }
                reader.readAsDataURL(file);
            }
        });
    });
</script>